### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'i'

### ISSUE THREAD

**Issue by attapap** [feyzikesim/sht20#3]
when I test my python file
the sht20 library has error line 7: ValueError: invalid literal for int() with base 10: 'i'

error:
pi@raspberrypi:~ $ sudo python /home/pi/SMARTGreenTable/sht20toLCD2004.py
-------Read Sensor-------
Traceback (most recent call last):
  File "/home/pi/SMARTGreenTable/sht20toLCD2004.py", line 54, in <module>
    temp = sht.read_temp()
  File "/home/pi/SMARTGreenTable/sht20.py", line 84, in read_temp
    temp_list.append(bytes_to_int(readTemp.buf[i]))
  File "/home/pi/SMARTGreenTable/sht20.py", line 7, in bytes_to_int
    result = result * 256 + int(b)
ValueError: invalid literal for int() with base 10: 'i'

please advise my,  how to correct this error?
thank :)

**Comment by Zbysekz** [comment]
Hello @attapap, i remember it happened to me also. I was running python2.7 instead python3. This library is supposed to be used with python3.

Altough it will probably work, if you modify code to convert bytes to int properly for 2.7.

**Comment by attapap** [comment]
def bytes_to_int(bytes):
    result = 0
    result = bytearray(bytes)
    #for b in bytes:
    #    result = result * 256 + int(b)
    return result[0]

[https://stackoverflow.com/questions/26121553/python-2-and-3-compatible-method-to-convert-bytes-to-integer](url)

Thanks :}
